#! /bin/bash
set -o errexit # -e
cd "$(dirname "$0")/.."

function ksh_syntax {
  for file in "$@"; do
    # Pipe stderr to awk
    ksh -n "${file}" 3>&2 2>&1 1>&3 |
      /usr/bin/awk '
        # \047 is the octal escape code for single quote
        /^(bbl|script\/release-notes): warning: line [[:digit:]]+: \047 quote may be missing$/ {next}
        {print}
      '
  done
}

function bash_syntax {
  for file in "$@"; do
    bash -n "${file}"
  done
}

# Use the ksh syntax checker on bash code, too. It is better than the
# built-in bash syntax checking. script/ contains only bash scripts.
ksh_syntax bbl script/*
bash_syntax script/*
