name: GitHub Actions CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install shfmt
        run: brew install shfmt

      - run: script/style
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install ksh93
        run: brew install ksh93

      - run: script/syntax
