name: GitHub Actions CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  style:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install shfmt
        run: brew install shfmt

      - run: script/style
